bot:
  token: "MTA3OTA2OTgxMDQ2MzM0Njc1OQ.GYuMII.unzZeMXUepBiu1FK7FrClqy3CqayXJHN8MdAJM"
  activitytype: "playing"
  activityname: "with your taser"
  status: "online"

database:
  host: "node-1.luftiger.eu"
  port: "3306"
  database: "s32_md_bot_test"
  username: "u32_lzaeGykL1H"
  password: "3yn%5Es!kiE8sbzvEcH!mh9wCn"
